---
- name: Install kubectl
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: 0755

- name: Install helm
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - helm
    - helm-zsh-completion
