---
- name: Add snappy repo
  community.general.zypper_repository:
    name: snappy
    repo: https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.3
    auto_import_keys: yes
    state: present

- name: Install snapd
  ansible.builtin.zypper:
    name: snapd
    state: present

- name: Start and enable snapd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - snapd
    - snapd.apparmor
